name: Persistent VPS

on:
  workflow_dispatch:  # Manual trigger only, NO automatic runs!

jobs:
  vps-session:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # Max allowed for GitHub-hosted runners

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set hostname to xclouds
        run: sudo hostnamectl set-hostname xclouds

      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt install -y tmate curl unzip sudo net-tools neofetch

      - name: neofetch for system info
        run: neofetch

      - name: Start tmate session for SSH access
        uses: mxschmitt/action-tmate@v3

      - name: Show system info
        run: |
          echo "RAM info:"
          free -h
          echo "Disk info:"
          df -h /
