name: Configure VPS with Tailscale

on:
  workflow_dispatch:

jobs:
  setup-vps:
    runs-on: ubuntu-latest
    steps:
      - name: Connect and configure VPS via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e
            # Install Tailscale if not present
            if ! command -v tailscale >/dev/null 2>&1; then
              curl -fsSL https://tailscale.com/install.sh | sh
            fi
            # Authenticate and bring up Tailscale
            sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTHKEY }}
            # Enable tailscaled to start on boot
            sudo systemctl enable tailscaled
            sudo systemctl restart tailscaled
            # Show Tailscale status and IP
            tailscale status
            tailscale ip -4
